//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int cID { get; set; }
        public Nullable<int> reservationID { get; set; }
        public Nullable<bool> refunded { get; set; }
        public string reason { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
