//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int ReservationID { get; set; }
        public string paymentType { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<double> totalPaid { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
